name: CI

on:
  push:
    branches: [main]        
  pull_request:

permissions:
  contents: write      # GitHub Release 생성
  id-token: write      # PyPI OIDC 인증
  packages: write      # GHCR 쓰려면 (선택)

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build deps
        run: |
          python -m pip install -U pip build

      - name: Build sdist & wheel
        run: python -m build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist
