name: Release

on:
  push:
    tags:
      - "v*"       # e.g. v1.2.3

permissions:
  contents: write      # create release
  id-token: write      # OIDC → PyPI
  actions: read        # download-artifact

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # OIDC 인증 → token 필요 없음
          packages_dir: dist
