name: Release

on:
  push:
    tags:
      - "v*"       # e.g. v1.2.3

permissions:
  contents: write      # create release
  id-token: write      # OIDC → PyPI
  actions: read        # download-artifact

name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
	 HEAD
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist


  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build distributions
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist
	 79387c9 (임시)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
<<<<<<< HEAD
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # OIDC 인증 → token 필요 없음
          packages_dir: dist
=======
          generate_release_notes: true
          files: dist/**
>>>>>>> 79387c9 (임시)
