name: Release

on:
  push:
    tags: ['v*']      # ex) v0.1.6

permissions:
  contents: write     # GitHub Release 업로드
  id-token: write     # PyPI trusted publishing(옵션)

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # build dists automatically (PEP 517); wheel+sdist upload

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
